MyPortfolio/Models/Contact.cs
using MongoDB.Bson;

namespace MyPortfolio.Models
{
    public class Contact
    {
        public ObjectId Id { get; set; }

        public string Email { get; set; }

        public string Name { get; set; }

        public Contact()
        {

        }

        public Contact(string email, string name)
        {
            Email = email;
            Name = name;
        }
    }
}

MyPortfolio/Models/ErrorViewModel.cs
namespace MyPortfolio.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MyPortfolio/Models/Project.cs
using MongoDB.Bson;

namespace MyPortfolio.Models
{
    public class Project
    {
        public ObjectId Id { get; set; }
        public string Name { get; set; }

        public string Description { get; set; }

        public int Level { get; set; }

        public string Link { get; set; }
    }
}

MyPortfolio/Controllers/ContactController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyPortfolio.Models;


namespace MyPortfolio.Controllers
{
    public class ContactController : Controller
    {
        public async Task<IActionResult> Index()

        {
            Mongodb db = new Mongodb();
            ViewBag.ContactSuccess = Request.Query["contact"] == "success";

            var contacts = await db.GetAllContacts();
            return View(contacts);

        }

        public async Task<IActionResult> PostContactAsync(Contact contact)
        {
            var db = new Mongodb();
            await db.SaveContact(contact);
            return Redirect("/Contact?contact=success");
        }
    }
}

MyPortfolio/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MyPortfolio.Models;
using System.Diagnostics;

namespace MyPortfolio.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyPortfolio/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using MyPortfolio;
using MyPortfolio.Models;

namespace Portfolio.Controllers
{
    public class ProjectController : Controller
    {
        public async Task<IActionResult> Index()
        {
            Mongodb db = new Mongodb();
            List<Project> projects = await db.GetAllProjects();
            return View(projects);
        }

        public async Task<IActionResult> Details(string id)
        {
            Mongodb db = new Mongodb();
            Project project = await db.GetProjectsById(id); 
            return View(project);   

        }

        public async Task<IActionResult> Delete(string id)
        {
            Mongodb db = new Mongodb();
            var project = await db.GetProjectsById(id);
            return View(project);

        }
        [HttpPost]
        public async Task<IActionResult> DeleteProject(string id)
        {
            Mongodb db = new Mongodb();
            await db.DeleteProject(id);
            return Redirect("/Project");    

        }

    }
}

MyPortfolio/Views/Contact/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<head>
    <link alt="stylesheet" src="~/css/StyleSheet.css" />
    <title>Contact</title>
</head>

<body>
    <div class="text-center">
        @if (ViewBag.ContactSuccess)
        {
            <h6>Tack för din kontakt!</h6>
        }



        <h1 class="display-4">Contact</h1>
        <p><strong>Mail:</strong> Sofia.Hjerpe@yahoo.com</p>
        <p><strong>Nummer:</strong> 0768882185</p>
        <p> <strong>GitHub:</strong> SofiaHjerpe</p>
        <p> <strong>Linkedin:</strong> Sofia Hjerpe</p>





    </div>

    <div style="margin-top: 20px" class="text-center">
        <h4>Contact me</h4>
        <form class="form" method="post" asp-action="PostContact">

            <div class="form-input">
                <label name="Name" class="control-label"></label>
                <input name="Name" placeholder="Name" />

            </div>
            <div class="form-input">
                <label name="Email" class="control-label"></label>
                <input name="Email" placeholder="Email" />

            </div>

            <button>Send</button>
        </form>


    </div>
</body>

MyPortfolio/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center" >
    <h1 class="display-4">Welcome</h1>
  
    <div class="white-box">
    <p style="display: flex; margin-inline: 20px">Hello! My name is Sofia and I am 23 years old. In the summer of 2022, I took my bachelor's degree from the ICT, media and design program at Södertörn University. During my education I learned more about programming. I have worked at Wellfish as a Junior Frontend developer. During my time at Wellfish, I learned more about structuring code. To do "push" and "commit" Gitlab was used. During my time at Wellfish, I learned more about the programming languages Vue.js, CSS, HTML, Javascript and Typescript. I also got to learn about Figma and CMS. I chose to quit working at Wellfish because I wanted a job with more collaboration. 
    I chose to quit working at Wellfish because I wanted to learn more about programming.
    Now I'm taking a course called "Programmering fortsättning" at Distansakademin. In the course I learn about the following programming languages; C#, HTML, Javascript, .Net Core WebAPI/MVC, Entity framework, Node js and Vue.js. 
    In the course I work with Mongodb, Visual Studio 2022, Github and Visual Studio Code.</p>


        <img style="width: 320px; height: 400px;  margin-inline: 20px" src="~/lib/image/image.JPG" />
        </div>

    </div>
    <style>
        
    </style>

MyPortfolio/Views/Project/Delete.cshtml
@model MyPortfolio.Models.Project

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Project</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Level)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Level)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Link)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Link)
        </dd>
    </dl>
    
    <form asp-action="DeleteProject" asp-route-id="@Model.Id.ToString()">
        <input type="submit" value="Delete" class="btn btn-danger" /> 
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MyPortfolio/Views/Project/Details.cshtml
@model MyPortfolio.Models.Project

@{
    ViewData["Title"] = "Details";
}

<h1 class="display-4">Details</h1>

<div>
    <h4> @Html.DisplayFor(model => model.Name)</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Level)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Level)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Link)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Link)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

MyPortfolio/Views/Project/Index.cshtml
@model IEnumerable<MyPortfolio.Models.Project>

@{
    ViewData["Title"] = "Index";
}
<head>
    <link alt="stylesheet" src="~/css/StyleSheet.css" />
    <title>Projects</title>
</head>
<body>
<h1 class="display-4">Projects</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Level)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Link)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Level)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Link)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new {  id=item.Id.ToString() })
            </td>
        </tr>
}
    </tbody>
</table>
 
</body>

MyPortfolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyPortfolio</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link rel="stylesheet" href="~/css/StyleSheet.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MyPortfolio.styles.css" asp-append-version="true" />
</head>

<header>
    <nav style="display:flex; align-items: center" class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="nav_wrap">
            <a class="navbar-brand" asp-area=""  asp-controller="Home" asp-action="Index">Sofia Hjerpe</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav ">
                    <li class="nav-item">
                        <h6>
                            <a class="link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </h6>
                    </li>

                    <li class="nav-item">
                        <h6>
                            <a class="link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Projects</a>
                        </h6>
                    </li>


                    <li class="nav-item">
                        <h6>
                            <a class="link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                        </h6>
                    </li>

                </ul>
            </div>
         
        </div>
        </header>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
<footer class="footer">



    <div class="footer_items">
        <a class="navbar-brand"  asp-area="" asp-controller="Home" asp-action="Index">Sofia Hjerpe</a>
        <div class="footer_item">
            <h6>Home</h6>
            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Welcome</a>
        </div>


        <div class="footer_item">
            <h6>Projects</h6>
            <a class="nav-link" asp-area="" asp-controller="Project" asp-action="Index">Projects</a>
        </div>



        <div class="footer_item">
            <h6>Contact</h6>
            <a class="nav-link" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
        </div>
    </div>

</footer>
</html>